apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: <%= appName %>
build:
  artifacts:
    - image: <%= appName %>/<%= appName %>
      jib:
        project: <%= packageName %>:<%= appName %>
